name: Infrastructure Apply

permissions:
  contents: write

env:
  AWS_REGION: eu-central-1

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.2
      # TODO: Should I move it somewhere else or whatever? Maybe I should have another place to create these kind of things; IAM, tfstate bucket
      - name: Create tfstate bucket if it is not exists
        run: |
          aws s3 ls | grep "${{ secrets.TFSTATE_BUCKET_NAME }}" || aws s3api create-bucket --bucket "${{ secrets.TFSTATE_BUCKET_NAME }}" --region "${{ secrets.AWS_REGION }}"
      - name: Terraform Apply
        env:
          TF_VAR_ENV: dev
          TF_VAR_FRONTEND_BUCKET_NAME: ${{ secrets.FRONTEND_BUCKET_NAME }}
          TF_VAR_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_AWS_REGION: ${{ env.AWS_REGION }}
          TF_VAR_ACCOUNT_NAME: ${{ secrets.AWS_ACCOUNT_NAME }}
        working-directory: deployment/frontend
        run: |
          terraform apply -lock=false --auto-approve
