name: Infrastructure Plan

permissions:
  contents: write

on:
  workflow_dispatch:

env:
  AWS_REGION: eu-central-1

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{env.AWS_REGION}}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.2
      - name: Terraform Plan
        env:
          TF_VAR_ENV: dev
          TF_VAR_FRONTEND_BUCKET_NAME: ${{secrets.FRONTEND_BUCKET_NAME}}
          TF_VAR_AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          TF_VAR_AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          TF_VAR_AWS_REGION: ${{env.AWS_REGION}}
          TF_VAR_ACCOUNT_NAME: ${{secrets.AWS_ACCOUNT_NAME}}
        working-directory: deployment/frontend
        # Save the result of plan in s3 bucket and use it in apply
        run: |
          terraform init
          terraform validate
          terraform plan -lock=false
